version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile_Frontend
    container_name: frontend
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile_Backend
    container_name: backend
    environment:
      - DOCKER=1
    depends_on:
      - database
  database:
    image: mongo
    environment:
      - DOCKER=1
    container_name: mongo-db
    volumes:
      - mongodb:/data/db
volumes:
    mongodb:
