version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile_Frontend
    ports:
      - "1000:1000"
    container_name: frontend
    environment:
        - VUE_APP_API_HOST_NAME=https://easy123.plenartech.com:2000
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile_Backend
    ports:
      - "2000:2000"
    container_name: backend
    environment:
      - FRONT_URL=http://easy123.plenartech.com:1000/
      - DOCKER=1
      - NODE_LOCAL_HOST=false
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - database
  database:
    image: mongo
    environment:
      - DOCKER=1
    container_name: mongo-db
    volumes:
      - mongodb:/data/db
volumes:
  mongodb: