<template>
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <h4 class="mt-3">Add Website <span v-if="selected_folder.name">to folder {{ selected_folder.name }}</span></h4>
      <form action="" @submit.prevent="addWebsite()">
        <div class="mb-3">
          <label for="text_to_put_on_button" class="form-label">Text to Put on Button</label>
          <input type="text" v-model="text_to_put_on_button" class="form-control" id="text_to_put_on_button" required>
          <small class="text-danger" v-if="text_to_put_on_button_error">{{ text_to_put_on_button_error }}</small>
        </div>
        <div class="mb-3">
          <label for="website_url" class="form-label">Website URL</label>
          <input type="text" v-model="website_url" class="form-control" id="website_url" @blur="getImageFromLink()" required>
          <small class="text-danger" v-if="website_url_error">{{ website_url_error }}</small>
        </div>
        <div class="mb-3">
          <label for="image_for_button" class="form-label">Image for button</label>
          <div class="row">
            <div class="col-md-6">
              <div v-if="website_autogenerated_image">
                <img src="@/assets/images/no-image.png" alt="" id="image_for_button" style="max-width: 200px; max-height: 152px;">
              </div>
              <div v-if="website_autogenerated_favicon">
                <img :src="website_sample_image_url" alt="" id="image_for_button_favicon" style="max-width: 200px; max-height: 152px;" v-if="!favicon_loading">
                <span v-if="favicon_loading">Loading...</span>
              </div>
              <div v-if="website_uploaded_image">
                <vue-dropzone
                    ref="avatarDropzone"
                    id="dropzone"
                    :options="dropzoneOptions"
                    @vdropzone-complete="handleVueDropzoneComplete"
                    class="mb-2"
                ></vue-dropzone>
              </div>

              <small class="text-danger" v-if="website_image_error">{{ website_image_error }}</small>
            </div>
            <div class="col-md-6">
              <a href="javascript:void(0)" class="btn btn-sm btn-outline-primary d-block mb-2" @click="useAutoGeneratedFavicon()">Use Favicon</a>
              <a href="javascript:void(0)" class="btn btn-sm btn-outline-primary d-block mb-2" @click="useUploadedImage()">Upload Image</a>
            </div>
          </div>
        </div>
        <div class="mb-3">
          <button class="btn btn-primary me-2" type="submit">Save</button>
          <button class="btn btn-secondary" @click="closeAddWebsiteForm">Close</button>
        </div>

      </form>
    </div>
  </div>
</template>

<script>
import axios from "axios";

export default {
  name: 'EasyWebImage',
  props: ['image', 'folderthumb'],
  data() {
    return {
      localImage: null,
      loading: false
    }
  },
  watch: {
    image: function (newVal)
    {
      this.formateImage(newVal)
      //this.localImage = newVal
    }
  },
  mounted() {
    this.formateImage(this.image)
    //this.localImage = this.image
  },
  methods: {
    formateImage(val) {
      let self = this
      //check if object
      if(val.imagePath)
      {
        if(val.imageData)
        {
          let b64 = 'data:'

          b64 = b64 + val.imageMimeType
          b64 = b64 + ';base64,'
          b64 = b64 + val.imageData
          self.localImage = b64
        }
        else
        {
          this.loading = true
          //check if image data is available
          axios.post(process.env.VUE_APP_API_HOST_NAME+"/api/get-private-image", {
            photo: {
              path: val.imagePath,
              name: val.imageFileName
            }
          }).then((response) => {
            self.loading = false
            let imageData = response.data.data

            let b64 = 'data:'

            b64 = b64 + val.imageMimeType
            b64 = b64 + ';base64,'
            b64 = b64 + imageData
            self.localImage = b64

          }, (error) => {
            console.log(error)
            self.loading = false
          })
        }



      }
      else
      {
        console.log("1 here", val)
        this.localImage = val.image
      }
    }
  }
}
</script>